USE WINFORM_DB;
GO

-- Перевірка та створення таблиці LOGIN_TBL
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'LOGIN_TBL')
BEGIN
    CREATE TABLE LOGIN_TBL (
        USERNAME VARCHAR(50) PRIMARY KEY,
        PASS VARCHAR(100) NOT NULL,
        PASSWORD_COMPLEXITY VARCHAR(10) NOT NULL,
        SECURITY_LEVEL VARCHAR(20) NOT NULL
    );
    PRINT 'Table LOGIN_TBL created successfully.';
END
ELSE
BEGIN
    PRINT 'Table LOGIN_TBL already exists.';
END
GO

-- Перевірка та створення таблиці FILE_ACCESS
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'FILE_ACCESS')
BEGIN
    CREATE TABLE FILE_ACCESS (
        FILE_NAME VARCHAR(100) PRIMARY KEY,
        CONFIDENTIALITY_LEVEL VARCHAR(20) NOT NULL
    );
    PRINT 'Table FILE_ACCESS created successfully.';
END
ELSE
BEGIN
    PRINT 'Table FILE_ACCESS already exists.';
END
GO

-- Перевірка та створення таблиці PASSWORD_HISTORY
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PASSWORD_HISTORY')
BEGIN
    CREATE TABLE PASSWORD_HISTORY (
        ID INT IDENTITY(1,1) PRIMARY KEY,
        USERNAME VARCHAR(50) NOT NULL,
        OLD_PASSWORD VARCHAR(100) NOT NULL,
        CHANGE_DATE DATETIME DEFAULT GETDATE()
    );
    PRINT 'Table PASSWORD_HISTORY created successfully.';
END
ELSE
BEGIN
    PRINT 'Table PASSWORD_HISTORY already exists.';
END
GO

-- Вставка даних у LOGIN_TBL
INSERT INTO LOGIN_TBL (USERNAME, PASS, PASSWORD_COMPLEXITY, SECURITY_LEVEL)
VALUES 
    ('Adm', 'Admin12345!', 'High', 'Administrative'),
    ('Yar1', 'Password1!', 'High', 'Top Secret'),
    ('Yar2', 'Password2@', 'High', 'Secret'),
    ('Yar3', 'Password3#', 'High', 'Confidential'),
    ('Yar4', 'Pass4', 'Low', 'FOUO'),
    ('Yar5', 'Pass5', 'Low', 'Unclassified');
GO

-- Виведення даних
SELECT * FROM LOGIN_TBL;
SELECT * FROM FILE_ACCESS;
SELECT * FROM PASSWORD_HISTORY;
GO

-- Очищення даних
 --DELETE FROM LOGIN_TBL;
 --DELETE FROM FILE_ACCESS;
-- DELETE FROM PASSWORD_HISTORY;
-- GO